get:
  summary: Get all Routes for Network Router
  description: |
    This endpoint retrieves all Routes for specified network router.
  operationId: getNetworkRoutersRoutes
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/routerId-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            type: object
            properties:
              networkRoutes:
                type: array
                items:
                  $ref: ../components/schemas/networkRouterRoute.yaml
          examples:
            Network Router Routes Response:
              value:
                $ref: ../components/examples/networkRoutersRoutes.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml

post: 
  summary: Create a Network Router Route
  description: Use this command to create a route for an existing network router.
  operationId: createNetworkRouterRoute
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/routerId-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties: 
            networkRoute:
              $ref: ../components/schemas/networkRouterRouteCreate.yaml
        examples: 
          Network  Router Request:
            value:
              $ref: ../components/examples/networkRouterRouteCreate.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/successId.yaml
          examples: 
            Successful Request:
              value:
                $ref: ../components/examples/successId.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
