get:
  summary: Download Image
  description: Downloads the specified image.
  operationId: getWhitelabelImage
  tags:
    - Whitelabel Settings
  parameters:
    - $ref: ../components/parameters/whitelabelImageType-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        image/ico:
          schema:
            type: string
            format: binary
        image/jpeg:
          schema:
            type: string
            format: binary
        image/png:
          schema:
            type: string
            format: binary
        image/svg+xml:
          schema:
            type: string
            format: binary
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
delete:
  summary: Reset Image
  description: Resets the specified image to the Morpheus default.
  operationId: removeWhitelabelImage
  tags:
    - Whitelabel Settings
  parameters:
    - $ref: ../components/parameters/whitelabelImageType-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml