get:
  summary: Get a Specific Deployment Version
  description: This endpoint retrieves a specific deployment version.
  operationId: getDeploymentVersion
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
    - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            type: object
            properties:
              version:
                $ref: ../components/schemas/deploymentVersion.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deploymentVersion.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
put:
  summary: Updating a Deployment Version
  description: This endpoint will update an existing deployment version.
  operationId: updateDeploymentVersion
  tags: 
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
    - $ref: ../components/parameters/id-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties:
            version:
              $ref: ../components/schemas/deploymentVersionCreate.yaml
        examples:
          Deployment Update:
            value:
              $ref: ../components/examples/deploymentVersionRequest.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf: 
            - type: object
              properties:
                version:
                  $ref: ../components/schemas/deploymentVersion.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Deployments Version Response:
              value:
                $ref: ../components/examples/deploymentVersionCreate.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
delete:
  summary: Delete a Deployment Version
  description: This endpoint will delete an existing deployment version.
  operationId: deleteDeploymentVersion
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
    - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Response:
              value:
                $ref: ../components/examples/success.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml