get:
  summary: Get Monitoring Settings
  description: This endpoint retrieves monitoring settings.
  operationId: getMonitoringSettings
  tags:
    - Monitoring Settings
  responses:
    '200':
      description: Monitoring Settings
      content:
        application/json:
          schema:
            type: object
            properties:
              monitoringSettings:
                $ref: ../components/schemas/monitoringSettings.yaml
          examples:
            Monitoring Settings Response:
              value:
                $ref: ../components/examples/monitoringSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
put:
  summary: Update Monitoring Settings
  description: Update Monitoring Settings
  operationId: updateMonitoringSettings
  tags:
    - Monitoring Settings
  requestBody:
    content:
      application/json:
        schema:
            type: object
            properties:
              monitoringSettings:
                $ref: ../components/schemas/monitoringSettings.yaml
  responses:
    '200':
      description: Update Monitoring Settings Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/200-success.yaml
          examples:
            Update User Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml