post:
  summary: Update Images
  description: Uploads whitelabel images. Expects multipart form data as the request format, not JSON.
  operationId: updateWhitelabelImages
  tags:
    - Whitelabel Settings
  requestBody:
    content:
      multipart/form-data: 
        schema: 
          type: object
          properties: 
            headerLogo.file:
              type: string
              format: binary
              description: Header logo image file, valid image types `png|jpg|svg`
            resetHeaderLogo:
              type: boolean
              description: Resets header logo to default
            footerLogo.file:
              type: string
              format: binary
              description: Footer logo image file, valid image types `png|jpg|svg`
            resetFooterLogo:
              type: boolean
              description: Resets footer logo to default
            loginLogo.file:
              type: string
              format: binary
              description: Login logo image file, valid image types `png|jpg|svg`
            resetLoginLogo:
              type: boolean
              description: Resets login logo to default
            favicon.file:
              type: string
              format: binary
              description: Favicon image file, valid image type ico
            resetFaviconLogo:
              type: boolean
              description: Resets favicon logo to default
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml