get:
  summary: Get Morpheus OpenAPI (Swagger) document as JSON.
  description: >-
    Get Morpheus OpenAPI (Swagger) document as JSON. This is the same document
    that you are reading at this very moment.
  operationId: docOpenapi
  tags:
    - Documentation
  security: []
  responses:
    '200':
      description: OpenAPI JSON specification for the Morpheus API
      content:
        application/json:
          examples:
            jsonExample:
              summary: OpenAPI (Swagger) JSON
              value:
                openapi: 3.1.0
                info:
                  title: Morpheus API
                  description: Welcome ...
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml