get:
  summary: Get a Specific Environment
  description: This endpoint will retrieve a specific environment by id.
  operationId: getEnvironments
  tags:
    - Environments
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Environment Object
      content:
        application/json:
          schema:
            type: object
            properties:
              environment:
                $ref: ../components/schemas/environment.yaml
          examples:
            Get Environment Response:
              value:
                $ref: ../components/examples/environment.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
put:
  summary: Update Environment
  description: Update an existing environment.
  operationId: updateEnvironments
  tags:
    - Environments
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - environment
          properties:
            environment:
              type: object
              description: Payload for updating a new environment
              properties:
                name:
                  type: string
                  description: A unique name for the environment
                  example: "Production"
                description:
                  type: string
                  description: A description of the environment
                  example: "Tag used for Production environments"
                visibility:
                  type: string
                  description: private or public
                  default: "private"
                sortOrder:
                  type: integer
                  format: int64
                  description: Sort order
                  default: 0
                active:
                  type: boolean
                  description: Set to false to deactivate the environment
                  example: true
  responses:
    '200':
      description: Environment Object
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                environment:
                  $ref: ../components/schemas/environment.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Update User Response:
              value:
                $ref: ../components/examples/environmentSuccess.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
delete:
  summary: Delete a Specific Environment
  description: Delete an existing environment.
  operationId: deleteEnvironments
  tags:
    - Environments
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Success Object
      content:
        application/json:
          schema:
            $ref: ../components/schemas/successError.yaml
          examples:
            Delete Environment Response:
              value:
                $ref: ../components/examples/successError.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml