get:
  summary: Get All Versions For a Deployment
  description: This endpoint returns a paginated list of versions for a specific deployment.
  operationId: listDeploymentVersions
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
    - $ref: ../components/parameters/max.yaml
    - $ref: ../components/parameters/offset.yaml
    - $ref: ../components/parameters/phrase.yaml
    - $ref: ../components/parameters/version.yaml
    - $ref: ../components/parameters/deploymentsDeployType.yaml
    - $ref: ../components/parameters/dateCreated.yaml
    - $ref: ../components/parameters/lastUpdated.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                versions:
                  type: array
                  items:
                    $ref: ../components/schemas/deploymentVersion.yaml
            - $ref: ../components/schemas/meta.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deploymentVersions.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
post: 
  summary: Create a new Deployment Version
  description: This endpoint will create a new deployment version that is ready to have files uploaded to it. The default type is file, which has files directly uploaded via Morpheus. Alternatively, the type git or fetch can be used to just point to a repository or remote url.
  operationId: addDeploymentVersion
  tags: 
    -  Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties: 
            version:
              $ref: ../components/schemas/deploymentVersionCreate.yaml
        examples:
          Deployment Request:
            value:
              $ref: ../components/examples/deploymentVersionRequest.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf: 
            - type: object
              properties:
                version:
                  $ref: ../components/schemas/deploymentVersion.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Deployments Version Response:
              value:
                $ref: ../components/examples/deploymentVersionCreate.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml