delete: 
  summary: Delete Deployment
  description: This endpoint deletes a specified deployment from a specified cluster.
  operationId: deleteClusterDeployment
  tags: 
    -  Clusters
  parameters:
    - $ref: ../components/parameters/clusterId-path.yaml
    - $ref: ../components/parameters/id-path.yaml
    - $ref: ../components/parameters/force.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Response:
              value:
                $ref: ../components/examples/success.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml