get:
  summary: Get all Routes for Network Router
  description: |
    This endpoint retrieves all Routes for specified network router.
  operationId: getNetworkRoutersRoutes
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/routerId-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            type: object
            properties:
              networkRoutes:
                type: array
                items:
                  $ref: ../components/schemas/networkRouterRoute.yaml
          examples:
            Network Router Routes Response:
              value:
                $ref: ../components/examples/networkRoutersRoutes.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml

post: 
  summary: Create a Network Router Route
  description: Use this command to create a route for an existing network router.
  operationId: createNetworkRouterRoute
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/routerId-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties: 
            networkRoute:
              $ref: ../components/schemas/networkRouterRouteCreate.yaml
        examples: 
          Network  Router Request:
            value:
              $ref: ../components/examples/networkRouterRouteCreate.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/successId.yaml
          examples: 
            Successful Request:
              value:
                $ref: ../components/examples/successId.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml