post:
  summary: Update Images
  description: Uploads whitelabel images. Expects multipart form data as the request format, not JSON.
  operationId: updateWhitelabelImages
  tags:
    - Whitelabel Settings
  requestBody:
    content:
      multipart/form-data: 
        schema: 
          type: object
          properties: 
            headerLogo.file:
              type: string
              format: binary
              description: Header logo image file, valid image types `png|jpg|svg`
            resetHeaderLogo:
              type: boolean
              description: Resets header logo to default
            footerLogo.file:
              type: string
              format: binary
              description: Footer logo image file, valid image types `png|jpg|svg`
            resetFooterLogo:
              type: boolean
              description: Resets footer logo to default
            loginLogo.file:
              type: string
              format: binary
              description: Login logo image file, valid image types `png|jpg|svg`
            resetLoginLogo:
              type: boolean
              description: Resets login logo to default
            favicon.file:
              type: string
              format: binary
              description: Favicon image file, valid image type ico
            resetFaviconLogo:
              type: boolean
              description: Resets favicon logo to default
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
