get:
  summary: Get Provisioning Settings
  description: This endpoint retrieves provisioning settings.
  operationId: listProvisioningSettings
  tags:
    - Provisioning Settings
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              provisioningSettings:
                $ref: ../components/schemas/provisioningSettings.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/provisioningSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml

put:
  summary: Update Provisioning Settings
  description: Update Provisioning Settings
  operationId: updateProvisioningSettings
  tags:
    - Provisioning Settings
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            provisioningSettings:
              $ref: ../components/schemas/provisioningSettingsUpdate.yaml
        examples:
          Provisioning Update Request:
            value:
              $ref: ../components/examples/provisioningSettingsUpdate.json
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml