get:
  summary: Get Appliance Settings
  description: This endpoint retrieves appliance settings.
  operationId: listApplianceSettings
  tags:
    - Appliance Settings
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              applianceSettings:
                $ref: ../components/schemas/applianceSettings.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/applianceSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml

put:
  summary: Update Appliance Settings
  description: Update Appliance Settings
  operationId: updateApplianceSettings
  tags:
    - Appliance Settings
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            applianceSettings:
              $ref: ../components/schemas/applianceSettingsUpdate.yaml
        examples:
          Appliance Update Request:
            value:
              $ref: ../components/examples/applianceSettingsUpdate.json
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
