get:
  summary: Get all Static Routes for a Network
  description: |
    This endpoint retrieves all routes for specified network.
  operationId: getStaticRoutes
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            type: object
            properties:
              networkRoutes:
                type: array
                items:
                  type: object
                  properties:
                    $ref: ../components/schemas/networkStaticRoute.yaml
          examples:
            Networks Response:
              value:
                $ref: ../components/examples/networkStaticRoutes.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml

put:
  summary: Create a Network Static Route
  description: |
    Use this command to create a route for an existing network.
  operationId: createStaticRoute
  tags:
    - Networks
  parameters:
    - $ref: ../components/parameters/id-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties: 
            networkRoute:
              $ref: ../components/schemas/networkStaticRouteCreate.yaml
        examples: 
          Successful Request:
            value: 
              $ref: ../components/examples/networkStaticRouteCreate.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/successId.yaml
          examples:
            Networks Response:
              value:
                $ref: ../components/examples/successId.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml