delete:
  summary: Delete a Specific Syslog Rule
  description: Will delete the syslog rule matching the specified name.
  operationId: deleteLogSettingsSyslogRules
  tags:
    - Administration
    - Log Settings
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Success Object
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Delete Syslog Rule Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml