get: 
  summary: Get Deployments
  description: This endpoint retrieves deployments of a specified cluster.
  operationId: listClusterDeployments
  tags: 
    -  Clusters
  parameters:
    - $ref: ../components/parameters/clusterId-path.yaml
    - $ref: ../components/parameters/max.yaml
    - $ref: ../components/parameters/offset.yaml
    - $ref: ../components/parameters/sort.yaml
    - $ref: ../components/parameters/order.yaml
    - $ref: ../components/parameters/phrase.yaml
    - $ref: ../components/parameters/resourceLevel.yaml
  responses:
    '200':
      description: Successful Request
      content: 
        application/json: 
          schema:
            allOf:
              - type: object
                properties:
                  deployments:
                    type: array
                    items:
                      $ref: ../components/schemas/clusterDeployments.yaml
              - $ref: ../components/schemas/meta.yaml
          examples:
            Cluster Request:
              value:
                $ref: ../components/examples/clusterDeployments.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml