delete:
  summary: Delete a Specific Syslog Rule
  description: Will delete the syslog rule matching the specified id.
  operationId: deleteLogSettingsSyslogRules
  tags:
    - Log Settings
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  responses:
    '200':
      description: Success Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/200-success.yaml
              - type: object
                properties:
                  msg:
                    type: string
                  errors:
                    type: object
                    additionalProperties:
                      type: string
          examples:
            Delete Syslog Rule Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
