get:
  summary: List All Log Settings
  description: This endpoint retrieves log settings.
  operationId: listLogSettings
  tags:
    - Log Settings
    - Administration
  responses:
    '200':
      description: Log Settings
      content:
        application/json:
          schema:
            type: object
            properties:
              logSettings:
                $ref: ../components/schemas/logSettings.yaml
          examples:
            Log Settings Response:
              value:
                $ref: ../components/examples/logSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
put:
  summary: Update Log Settings
  description: Update Log Settings
  operationId: updateLogSettings
  tags:
    - Administration
    - Log Settings
  requestBody:
    content:
      application/json:
        schema:
            type: object
            properties:
              logSettings:
                $ref: ../components/schemas/logSettings.yaml
  responses:
    '200':
      description: Update Log Settings Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/user.yaml
              - $ref: ../components/schemas/200-success.yaml
          examples:
            Update User Response:
              value:
                $ref: ../components/examples/userSuccess.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml