get:
  summary: List All Environments
  description: This endpoint retrieves all environments.
  operationId: listEnvironments
  tags:
    - Environments
  parameters:
    - $ref: ../components/parameters/max.yaml
    - $ref: ../components/parameters/offset.yaml
    - $ref: ../components/parameters/sort.yaml
    - $ref: ../components/parameters/direction.yaml
    - $ref: ../components/parameters/phrase.yaml
    - $ref: ../components/parameters/name.yaml
    - $ref: ../components/parameters/code.yaml
  responses:
    '200':
      description: Array of Environments
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                environments:
                  type: array
                  items:
                    $ref: ../components/schemas/environment.yaml
            - $ref: ../components/schemas/meta.yaml
          examples:
            Users Response:
              value:
                $ref: ../components/examples/environments.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
post:
  summary: Create a New Environment
  description: Create a new environment.
  operationId: addEnvironments
  tags:
    - Environments
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - environment
          properties:
            environment:
              type: object
              description: Payload for creating a new environment
              required:
                - name
                - code
              properties:
                name:
                  type: string
                  description: A unique name for the environment
                  example: "Production"
                code:
                  type: string
                  description: A unique code for the environment
                  example: "prod"
                description:
                  type: string
                  description: A description of the environment
                  example: "Tag used for Production environments"
                visibility:
                  type: string
                  description: private or public
                  default: "private"
                sortOrder:
                  type: integer
                  format: int64
                  description: Sort order
                  default: 0
  responses:
    '200':
      description: Environment Object
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                environment:
                  $ref: ../components/schemas/environment.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Create Environment Response:
              value:
                $ref: ../components/examples/environmentSuccess.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml