get:
  summary: Get Whitelabel Settings
  description: This endpoint retrieves whitelabel settings.
  operationId: listWhitelabelSettings
  tags:
    - Whitelabel Settings
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              whitelabelSettings:
                $ref: ../components/schemas/whitelabelSettings.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/whitelabelSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml

put:
  summary: Update Whitelabel Settings
  description: Update Whitelabel Settings
  operationId: updateWhitelabelSettings
  tags:
    - Whitelabel Settings
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            whitelabelSettings:
              $ref: ../components/schemas/whitelabelSettingsUpdate.yaml
        examples:
          Whitelabel Update Request:
            value:
              $ref: ../components/examples/whitelabelSettingsUpdate.json
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml