get:
  summary: Get All Deployments
  description: This endpoint returns a paginated list of deployments.
  operationId: listDeployments
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/max.yaml
    - $ref: ../components/parameters/offset.yaml
    - $ref: ../components/parameters/phrase.yaml
    - $ref: ../components/parameters/name.yaml
    - $ref: ../components/parameters/description.yaml
    - $ref: ../components/parameters/dateCreated.yaml
    - $ref: ../components/parameters/lastUpdated.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                deployments:
                  type: array
                  items:
                    $ref: ../components/schemas/deployments.yaml
            - $ref: ../components/schemas/meta.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deployments.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
post: 
  summary: Create a new Deployment
  description: This endpoint will create a new deployment that is ready to have versions added to it.
  operationId: addDeployments
  tags: 
    -  Deployments
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties: 
            deployment:
              $ref: ../components/schemas/deploymentCreate.yaml
        examples:
          Deployment Request:
            value:
              $ref: ../components/examples/deploymentRequest.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf: 
            - type: object
              properties:
                deployment:
                  $ref: ../components/schemas/deploymentCreateSuccess.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deploymentCreateSuccess.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml