get:
  summary: Get a Specific Deployment
  description: This endpoint retrieves a specific deployment. By default the 5 most recent versions are returned, more can be returned by specifying the maxVersions parameter.
  operationId: getDeployment
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
    - $ref: ../components/parameters/maxVersions.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            type: object
            properties:
              deployment:
                $ref: ../components/schemas/deployment.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deployment.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
put:
  summary: Updating a Deployment
  description: This endpoint will update an existing deployment.
  operationId: updateDeployment
  tags: 
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
  requestBody: 
    content: 
      application/json: 
        schema: 
          type: object
          properties:
            deployment:
              $ref: ../components/schemas/deploymentCreate.yaml
        examples:
          Deployment Update:
            value:
              $ref: ../components/examples/deploymentRequest.json
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            allOf: 
            - type: object
              properties:
                deployment:
                  $ref: ../components/schemas/deployment.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Deployments Response:
              value:
                $ref: ../components/examples/deploymentUpdate.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
delete:
  summary: Delete a Deployment
  description: This endpoint will delete an existing deployment.
  operationId: deleteDeployment
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/deploymentId-path.yaml
  responses:
    '200':
      description: Successful Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Response:
              value:
                $ref: ../components/examples/success.json 
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml