get:
  summary: Get Backup Settings
  description: This endpoint retrieves backup settings.
  operationId: listBackupSettings
  tags:
    - Backup Settings
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              backupSettings:
                $ref: ../components/schemas/backupSettings.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/backupSettings.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml
put:
  summary: Update Backup Settings
  description: Update Backup Settings
  operationId: updateBackupSettings
  tags:
    - Backup Settings
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            backupSettings:
              $ref: ../components/schemas/backupSettingsUpdate.yaml
        examples:
          Backup Update Request:
            value:
              $ref: ../components/examples/backupSettingsUpdate.json
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/200-success.yaml
          examples:
            Successful Response:
              value:
                $ref: ../components/examples/success.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml