get: 
  summary: Get Ingresses
  description: This endpoint retrieves ingresses of a specified cluster.
  operationId: listClusterIngresses
  tags: 
    - Clusters
  parameters:
    - $ref: ../components/parameters/clusterId-path.yaml
  responses:
    '200':
      description: Successful Request
      content: 
        application/json: 
          schema:
            allOf:
              - type: object
                properties:
                  replicasets:
                    type: array
                    items:
                      $ref: ../components/schemas/clusterResources.yaml
              - $ref: ../components/schemas/meta.yaml
          examples:
            Cluster Request:
              value:
                $ref: ../components/examples/clusterIngresses.json
    '4XX':
      $ref: ../components/responses/4xx.yaml
    '5XX':
      $ref: ../components/responses/5xx.yaml