type: object
properties:
  uuid:
    type: string
  applianceId:
    type: string
  applianceUrl:
    type: string
  internalApplianceUrl:
    type: string
  corsAllowed:
    type: string
  registrationEnabled:
    type: boolean
  defaultRoleId:
    type: string
  defaultUserRoleId:
    type:
      - string
      - 'null'
  dockerPrivilegedMode:
    type: boolean
  cloudSyncIntervalSeconds:
    type:
      - string
      - 'null'
  clusterSyncIntervalSeconds:
    type:
      - string
      - 'null'
  usageRetainmentPeriod:
    type:
      - string
      - 'null'
  invoiceRetainmentPeriod:
    type:
      - string
      - 'null'
  incidentRetainmentPeriod:
    type:
      - string
      - 'null'
  statsRetainmentPeriod:
    type:
      - string
      - integer
      - 'null'
  reportsRetainmentPeriod:
    type:
      - string
      - 'null'
  httpBlacklistHosts:
    type:
      - string
      - 'null'
  httpApprovelistHosts:
    type:
      - string
      - 'null'
  exchangeUrl:
    type:
      - string
      - 'null'
  noAgent:
    type: boolean
  agentSSLVerify:
    type: boolean
  disableSSHPasswordAuth:
    type: boolean
  defaultLocale:
    type:
      - string
      - 'null'
  defaultVdiGateway:
    type:
      - string
      - 'null'
  maxOptionListSize:
    type:
      - string
      - 'null'
  passwordMinLength:
    type:
      - string
      - 'null'
  passwordMinUpperCase:
    type:
      - string
      - 'null'
  passwordMinNumbers:
    type:
      - string
      - 'null'
  passwordMinSymbols:
    type:
      - string
      - 'null'
  userBrowserSessionTimeout:
    type:
      - string
      - 'null'
  userBrowserSessionWarning:
    type:
      - string
      - 'null'
  expirePwdDays:
    type:
      - string
      - 'null'
  disableAfterAttempts:
    type:
      - string
      - 'null'
  disableAfterDaysInactive:
    type:
      - string
      - 'null'
  warnUserDaysBefore:
    type:
      - string
      - 'null'
  smtpMailFrom:
    type:
      - string
      - 'null'
  smtpServer:
    type:
      - string
      - 'null'
  smtpPort:
    type:
      - string
      - 'null'
  smtpSSL:
    type: boolean
  smtpTLS:
    type: boolean
  smtpUser:
    type:
      - string
      - 'null'
  smtpPassword:
    type:
      - string
      - 'null'
  smtpPasswordHash:
    type:
      - string
      - 'null'
  twilioAccountSid:
    type:
      - string
      - 'null'
  twilioSmsFrom:
    type:
      - string
      - 'null'
  twilioAuthToken:
    type:
      - string
      - 'null'
  proxyHost:
    type:
      - string
      - 'null'
  proxyPort:
    type:
      - string
      - 'null'
  proxyUser:
    type:
      - string
      - 'null'
  proxyPassword:
    type:
      - string
      - 'null'
  proxyPasswordHash:
    type:
      - string
      - 'null'
  proxyDomain:
    type:
      - string
      - 'null'
  proxyWorkstation:
    type:
      - string
      - 'null'
  noProxy:
    type:
      - string
      - 'null'
  currencyProvider:
    type:
      - string
      - 'null'
  currencyKey:
    type:
      - string
      - 'null'
  maintenanceMode:
    type: boolean
  enabledZoneTypes:
    type:
      - array
      - 'null'
    items:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  dashboardsToDisplay:
    type:
      - string
      - 'null'
  enableMurph:
    type: boolean
  vmeAppliance:
    type: boolean
  latestWindowsAgentVersion:
    type: string
  latestLinuxAgentVersion:
    type: string
