type: object
properties: 
  uuid: 
    type: string
  applianceId: 
    type: string
  applianceUrl: 
    type: string
  internalApplianceUrl: 
    type: string
  corsAllowed: 
    type: string
  registrationEnabled: 
    type: boolean
  defaultRoleId: 
    type: string
  defaultUserRoleId: 
    type: string
    nullable: true
  dockerPrivilegedMode: 
    type: boolean
  expirePwdDays: 
    type: string
    nullable: true
  disableAfterAttempts: 
    type: string
    nullable: true
  disableAfterDaysInactive: 
    type: string
    nullable: true
  warnUserDaysBefore: 
    type: string
    nullable: true
  smtpMailFrom: 
    type: string
    nullable: true
  smtpServer: 
    type: string
    nullable: true
  smtpPort: 
    type: string
    nullable: true
  smtpSSL: 
    type: boolean
  smtpTLS: 
    type: boolean
  smtpUser: 
    type: string
    nullable: true
  smtpPassword: 
    type: string
    nullable: true
  smtpPasswordHash: 
    type: string
    nullable: true
  proxyHost: 
    type: string
    nullable: true
  proxyPort: 
    type: string
    nullable: true
  proxyUser: 
    type: string
    nullable: true
  proxyPassword: 
    type: string
    nullable: true
  proxyPasswordHash: 
    type: string
    nullable: true
  proxyDomain: 
    type: string
    nullable: true
  proxyWorkstation: 
    type: string
    nullable: true
  currencyProvider: 
    type: string
    nullable: true
  currencyKey: 
    type: string
    nullable: true
  enabledZoneTypes: 
    type: array
    nullable: true
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        name: 
          type: string
  statsRetainmentPeriod:
    type: integer
    format: int64