type: object
properties: 
  uuid: 
    type: string
  applianceId: 
    type: string
  applianceUrl: 
    type: string
  internalApplianceUrl: 
    type: string
  corsAllowed: 
    type: string
  registrationEnabled: 
    type: boolean
  defaultRoleId: 
    type: string
  defaultUserRoleId: 
    type: [ string, 'null' ]
  dockerPrivilegedMode: 
    type: boolean
  expirePwdDays: 
    type: [ string, 'null' ]
  disableAfterAttempts: 
    type: [ string, 'null' ]
  disableAfterDaysInactive: 
    type: [ string, 'null' ]
  warnUserDaysBefore: 
    type: [ string, 'null' ]
  smtpMailFrom: 
    type: [ string, 'null' ]
  smtpServer: 
    type: [ string, 'null' ]
  smtpPort: 
    type: [ string, 'null' ]
  smtpSSL: 
    type: boolean
  smtpTLS: 
    type: boolean
  smtpUser: 
    type: [ string, 'null' ]
  smtpPassword: 
    type: [ string, 'null' ]
  smtpPasswordHash: 
    type: [ string, 'null' ]
  proxyHost: 
    type: [ string, 'null' ]
  proxyPort: 
    type: [ string, 'null' ]
  proxyUser: 
    type: [ string, 'null' ]
  proxyPassword: 
    type: [ string, 'null' ]
  proxyPasswordHash: 
    type: [ string, 'null' ]
  proxyDomain: 
    type: [ string, 'null' ]
  proxyWorkstation: 
    type: [ string, 'null' ]
  currencyProvider: 
    type: [ string, 'null' ]
  currencyKey: 
    type: [ string, 'null' ]
  enabledZoneTypes: 
    type: [ array, 'null' ]
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        name: 
          type: string
  statsRetainmentPeriod:
    type: integer
    format: int64
