type: object
required:
  - webMethod
  - webUrl
properties:
  webMethod:
    type: string
    description: HTTP method to use for testing
    enum:
      - GET
      - POST
  webUrl:
    type: string
    description: Web URL you wish to use to run a check on
    example: 'https://google.com'
  ignoreSSL:
    type: boolean
    description: Ignore SSL Errors
    example: true
    default: false
  checkUser:
    type: string
    description: If you want to use HTTP Basic Authentication, populate this field with the username
    example: basicUser
  checkPassword:
    type: string
    description: If you want to use HTTP basic Authentication, populate this field with the password
    example: basicPassword
  textCheckOn:
    type: string
    description: Set value to `on` if you want to turn on text matching
    example: on
  webTextMatch:
    type: string
    description: Set the string you want to look for in the page source
    example: Login
  tunnelOn: 
    type: string
    description: Set to on to turn on tunneling
    enum:
      - on
      - off
  sshHost: 
    type: string
    description: Hostname or IP address of the proxy host
  sshPort: 
    type: integer
    format: int64
    description: Port for SSH on the proxy host, defaults to 22
  sshUser: 
    type: string
    description: SSH user on the proxy host to login as
  sshPassword:
    type: string
    description: Password for user, if not using key based authentication
