type: object
required:
  - containerName
properties:
  containerName: 
    type: string
  externalId: 
    type: string
    nullable: true
  checkUser: 
    type: string
  textCheckOn: 
    type: string
  checkPassword: 
    type: string
  webTextMatch: 
    type: string
  checkPasswordHash: 
    type: string
  tunnelOn: 
    type: string
    description: Set to on to turn on tunneling
    enum:
      - on
      - off
    default: off
  sshHost: 
    type: string
    description: Hostname or IP address of the proxy host
  sshPort: 
    type: integer
    format: int64
    description: Port for SSH on the proxy host, defaults to 22
  sshUser: 
    type: string
    description: SSH user on the proxy host to login as
  sshPassword:
    type: string
    description: Password for user, if not using key based authentication