type: object
required:
  - port
  - host
  - send
  - responseMatch
properties: 
  host:
    type: string
    description: Hostname or IP address of the socket server
    example: "test.example.org"
  port:
    type: string
    description: TCP port
    example: '3306'
  send:
    type: string
    description: Connection string you might want to send to the service
    example: blah
  responseMatch:
    type: string
    description: Response from the service to match against
    example: OK