type: object
required:
  - port
  - host
  - send
  - responseMatch
properties: 
  host:
    type: string
    description: Hostname or IP address of the socket server
    example: "test.example.org"
  port:
    type: string
    description: TCP port
    example: '3306'
  send:
    type: string
    description: Connection string you might want to send to the service
    example: blah
  responseMatch:
    type: string
    description: Response from the service to match against
    example: OK
  checkUser: 
    type: string
  textCheckOn: 
    type: string
  checkPassword: 
    type: string
  webTextMatch: 
    type: string
  checkPasswordHash: 
    type: string
  tunnelOn: 
    type: string
    description: Set to on to turn on tunneling
    enum:
      - on
      - off
    default: off
  sshHost: 
    type: string
    description: Hostname or IP address of the proxy host
  sshPort: 
    type: integer
    format: int64
    description: Port for SSH on the proxy host, defaults to 22
  sshUser: 
    type: string
    description: SSH user on the proxy host to login as
  sshPassword:
    type: string
    description: Password for user, if not using key based authentication