type: object
required:
  - containerName
properties:
  containerName: 
    type: string
  externalId: 
    type: string
    nullable: true
  sshPort: 
    type: integer
    format: int64
  checkUser: 
    type: string
  tunnelOn: 
    type: string
  textCheckOn: 
    type: string
  checkPassword: 
    type: string
  sshHost: 
    type: string
  sshUser: 
    type: string
  webTextMatch: 
    type: string
  checkPasswordHash: 
    type: string
  