type: object
required:
  - esHost
  - esPort
properties: 
  esHost:
    type: string
    description: Hostname or IP address of the Elasticsearch server
    example: "test.example.org"
  esPort:
    type: string
    description: Port to connect to the HTTP service
    example: "9200"
  sshPort: 
    type: integer
    format: int64
  checkUser: 
    type: string
  tunnelOn: 
    type: string
  textCheckOn: 
    type: string
  checkPassword: 
    type: string
  sshHost: 
    type: string
  sshUser: 
    type: string
  webTextMatch: 
    type: string
  checkPasswordHash: 
    type: string
