type: object
required:
  - containerName
properties:
  containerName:
    type: string
  externalId:
    type:
      - string
      - 'null'
  checkUser:
    type: string
  textCheckOn:
    type: string
  checkPassword:
    type: string
  webTextMatch:
    type: string
  checkPasswordHash:
    type: string
