title: SNMP Config
type: object
required:
  - host
  - port
properties:
  host:
    type: string
    description: Hostname or IP address of the SNMP network entity
    example: "test.example.org"
  port:
    type: string
    description: Port to connect to the SNMP entity
    example: "161"
  oid:
    type: string
    description: Object ID to get from the network entity
    example: .1.3.6.1.2.1.1.5.0
  checkOperator:
    type: string
    description: Operator to use when comparing returned value with the expected check response value. One of 'lt', 'equal', or 'gt'.
  checkResponse:
    type: string
    description: Value to use with the check operator
  version:
    type: string
    description: SNMP Version 1/2c/3 of snmp get command
    enum:
      - "1"
      - "2c"
      - "3"
  community:
    description: Community string acts as simple user or ID password (only valid for v1/2c)
    type: string
  username:
    type: string
    description: Username used with SNMPv3 auth/privacy protocol passwords
  securityLevel:
    type: string
    description: Level of security for authentication and privacty
    enum:
      - noAuthNoPriv
      - authNoPriv
      - authPriv
  auth:
    type: string
    description: Authentication protocol
    enum:
      - MD5
      - SHA
      - SHA-224
      - SHA-256
      - SHA-384
      - SHA-512      
  authpassword:
    type: string
  priv:
    type: string
    description: Privacy protocol
    enum:
      - DES
      - AES
      - AES-192
      - AES-256
  privpassword:
    type: string
  sshHost: 
    type: string
    description: Hostname or IP address of the proxy host
  sshPort: 
    type: integer
    format: int64
    description: Port for SSH on the proxy host, defaults to 22
  sshUser: 
    type: string
    description: SSH user on the proxy host to login as
  sshPassword:
    type: string
    description: Password for user, if not using key based authentication
