description: HVM Cloud
type: object
properties:
  certificateProvider:
    type: string
    description: Certificate provider
  enableNetworkTypeSelection:
    type: boolean
    description: Enable network type selection
