description: HVM Cloud
type: object
properties:
  certificateProvider:
    type: string
    description: Certificate provider
    default: internal
  enableNetworkTypeSelection:
    oneOf: 
      - type: string
        enum:
          - on
      - type: 'null'
    default: null
    description: Enable network type selection
