description: Amazon Cloud
type: object
required:
  - endpoint
properties:
  applianceUrl:
    type: string
    description: The URL used by workloads provisioned in the cloud for interacting with the Morpheus appliance.
  datacenterName:
    type: string
    description: A custom name used to reference the datacenter for the cloud.
  externalId:
    type:
      - string
      - 'null'
    description: The external id of the cloud
  inventoryLevel:
    type: string
    enum:
      - off
      - basic
      - full
    description: Whether to import existing virtual machines.
  consoleKeymap:
    type: string
    description: The keyboard layout to use for the console
  endpoint:
    type: string
    description: AWS endpoint
    example: ec2.ca-central-1.amazonaws.com
  accessKey:
    type: string
    description: AWS access key
  secretKey:
    type: string
    description: AWS secret key
  useHostCredentials:
    type: string
    enum:
      - on
      - off
    description: Whether to use the IAM profile associated with the Morpheus server or not
    default: on
    example: on
  ebsEncryption:
    type: string
    enum:
      - on
      - off
    description: Determines whether to configure default EBS volume encryption or not
    default: on
    example: on
  stsAssumeRole:
    type: string
    description: The AWS IAM role ARN to assume for authentication
  configManagementId:
    type: string
    description: The id of the configuration management integration associated with the AWS cloud
  vpc:
    type: string
    description: The VPC ID for a specific VPC
    example: vpc-25e6dae
  vdiGateway:
    type: string
    description: The VDI gateway for this cloud to use for provisioning virtual desktops.
  cmdbConfig:
    type: string
    description: The CMDB configuration for this cloud to use for syncing with the CMDB.
  changeManagementConfig:
    type: string
    description: The change management configuration for this cloud to use for syncing with the change management system.
  networkMode:
    type:
      - string
      - 'null'
    description: Whether to use public or private IP addresses for provisioning and managing instances in this cloud.
  apiProxy:
    type: 
      - string
      - 'null'
    description: The API proxy to use for API calls to the cloud.
  region:
    type: string
    description: The AWS region to use for this cloud.
  credentials:
    type: string
    description: The credentials to use for this cloud.
  costingBucket:
    type: string
    description: The S3 bucket to use for storing costing reports.
  costingFolder:
    type: 
      - string
      - 'null'
    description: The folder within the S3 bucket to use for storing costing reports.
  costingReportName:
    type:  
      - string
      - 'null'
    description: The name of the costing report to generate.
  costingKey:
    type: 
      - string
      - 'null'
    description: The AWS access key to use for generating costing reports.
  costingSecret:
    type: 
      - string
      - 'null'
    description: The AWS secret key to use for generating costing reports.
  domain:
    type: string
    description: The domain to use for this cloud.
  timezone:
    type: string
    description: The timezone to use for this cloud.
  securityServer:
    type: string
    description: The security server to use for this cloud, or 'off' to not use a security server.
  guidance:
    type: string
    enum:
      - off
      - manual
    description: Optional guidance field if you want to put more info there
  costing:
    type: string
    enum:
      - costing
      - reservations
      - costing and reservations
    description: Whether to enable costing for this cloud or not.
  configCmdbDiscovery:
    type: string
    enum:
      - on
      - off
    description: The CMDB discovery configuration to use for this cloud.
  logo:
    type: 
      - string
      - 'null'
    description: The logo to use for this cloud.
  darkModeLogo:
    type: 
      - string
      - 'null'
    description: The logo to use for this cloud in dark mode.
  proxy:
    type: string
    description: The proxy to use for this cloud.
  bypassProxyForCloud:
    type: string
    enum:
      - on
      - off
    description: Whether to bypass the proxy for API calls to the cloud or not.
  noProxy:
    type: string
    description: A comma separated list of hosts to bypass the proxy for when making API calls to the cloud.
  userDataLinux:
    type: string
    description: The user data script to use for provisioning instances in this cloud.
