description: Amazon Cloud
type: object
properties:
  endpoint:
    type: string
    description: AWS endpoint
    example: ec2.ca-central-1.amazonaws.com
  accessKey:
    type: string
    description: AWS access key
  secretKey:
    type: string
    description: AWS secret key
  useHostCredentials:
    type: string
    enum:
      - on
      - off
    description: Whether to use the IAM profile associated with the Morpheus server or not
    default: on
    example: on
  ebsEncryption:
    type: string
    enum:
      - on
      - off
    description: Determines whether to configure default EBS volume encryption or not
    default: on
    example: on
  stsAssumeRole:
    type: string
    description: The AWS IAM role ARN to assume for authentication
  configManagementId:
    type: string
    description: The id of the configuration management integration associated with the AWS cloud
  vpc:
    type: string
    description: The VPC ID for a specific VPC
    example: vpc-25e6dae
