description: Configuration for HVM cluster servers
type: object
properties:
  $ref: clusterServerCreateConfigCommon.yaml
  cpuArch:
    type: string
  cpuModel:
    type: string
  dynamicPlacementMode:
    type: string
    enum:
      - on
      - off
  powerPolicy:
    type: string
    enum:
    - balanced
    - performance
  storageInterfaceName:
    type: string
  computeInterfaceName:
    type: string
  computeVlans:
    type: string
  overlayInterfaceName:
    type: string
  createUser:
    type: boolean
