description: Configuration for HKS cluster servers provisioned using HVM
type: object
properties:
  $ref: clusterServerCreateConfigCommon.yaml
  podCidr:
    type: string
  serviceCidr:
    type: string
  nodeCount:
    type: integer
    format: int64
  createUser:
    type: boolean
