description: Configuration for Google Kuberenetes Engine cluster servers
type: object
properties:
  googleZoneId:
    type: integer
    format: int64
  worker:
    type: object
    properties:
      plan:
        type: object
        properties:
          id:
            type: integer
            format: int64
  channel:
    type: string
  controlPlaneVersion:
    type: string
  nodeCount:
    type: integer
    format: int64
  createUser:
    type:
      - bool
      - 'null'
