description: Configuration for VMware cluster servers
type: object
properties:
  $ref: clusterServerCreateConfigCommon.yaml
  nodeCount:
    type: integer
    format: int64
    description: Number of workers or hosts
  podCidr:
    type: string
  vmwareFolderId:
    type: string
  serviceCidr:
    type: string
  createUser:
    type: boolean
