description: Configuration for HKS cluster servers
type: object
properties:
  $ref: clusterServerCreateConfigCommon.yaml
  podCidr:
    type: string
  serviceCidr:
    type: string
  createUser:
    type: boolean
