type: object
properties:
  serviceUrl: 
    type: [ string, 'null' ]
  serviceHost: 
    type: [ string, 'null' ]
  servicePath: 
    type: [ string, 'null' ]
  serviceHostname: 
    type: [ string, 'null' ]
  servicePort: 
    type: integer
    format: int64
  serviceUsername: 
    type: [ string, 'null' ]
  servicePassword: 
    type: [ string, 'null' ]
  servicePasswordHash: 
    type: [ string, 'null' ]
  serviceToken: 
    type: [ string, 'null' ]
    description: API Token
  serviceAccess: 
    type: [ string, 'null' ]
    description: Kube Config
  serviceCert: 
    type: [ string, 'null' ]
  serviceVersion: 
    type: [ string, 'null' ]
