required:
  - username
  - password
properties:
  username:
    type: string
    description: Username
    example: jsmith
  password:
    type: string
    description: User password, API Key, or applicable secret
    example: myPassword