required:
  - username
  - password
  - authKey
properties:
  username:
    type: string
    description: Username
    example: jsmith
  password:
    type: string
    description: User password, API Key, or applicable secret
    example: myPassword
  authKey:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        description: Private Key ID of a `Key Pair`
        example: 9