required:
  - authPath
  - username
  - password
properties:
  authPath:
    type: string
    description: Tenant name
    example: My Tenant
  username:
    type: string
    description: Username
    example: jsmith
  password:
    type: string
    description: User password, API Key, or applicable secret
    example: myPassword