required:
  - username
  - password
  - config
properties:
  username:
    type: string
    description: Username
    example: jsmith
  password:
    type: string
    description: User password, API Key, or applicable secret
    example: myPassword
  config:
    type: object
    required:
      - grantType
      - accessTokenUrl
      - clientAuth
    properties:
      grantType:
        type: string
        description: OAuth 2.0 grant type
        enum:
        - password
        - client_credentials
      accessTokenUrl:
        type: string
        description: Token endpoint
        example: 'https://example.com'
      clientId:
        type: string
        description: Client ID
        example: myclientid12345
      clientSecret:
        type: string
        description: Client Secret
        example: myclientsecret12345
      scope:
        type: string
        description: Scope
        example: read
      clientAuth:
        type: string
        description: Client Authentication Method
        enum:
        - body
        - basic-auth