type: object
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  description:
    type:
      - string
      - 'null'
  accountId:
    type: integer
    format: int64
  externalId:
    type:
      - string
      - 'null'
  dateCreated:
    type: string
    format: date-time
  lastUpdated:
    type: string
    format: date-time
  versionCount:
    type: integer
    format: int64
