type: object
properties:
  id:
    type: integer
    format: int64
  deployType:
    type: string
  deploymentId:
    type: integer
    format: int64
  fetchUrl:
    type:
      - string
      - 'null'
  gitUrl:
    type:
      - string
      - 'null'
  gitRef:
    type:
      - string
      - 'null'
  userVersion:
    type: string
  version:
    type: string
  status:
    type: string
  dateCreated:
    type: string
    format: date-time
  lastUpdated:
    type: string
    format: date-time
