type: object
properties:
  id: 
    type: integer
    format: int64
  name: 
    type: string
  description: 
    type: string
    nullable: true
  accountId: 
    type: integer
    format: int64
  externalId: 
    type: string
    nullable: true
  dateCreated: 
    type: string
  lastUpdated: 
    type: string
  versionCount: 
    type: integer
    format: int64