type: object
properties:
  version:
    type: string
    description: Version number (userVersion), a unique version identifier for the deployment version.
  userVersion:
    type: string
    description: Alias for version
  deployType:
    type: string
    description: Deploy Type, eg. file, git, fetch
    enum:
      - file
      - git
      - fetch
  gitUrl:
    type:
      - string
      - 'null'
  gitRef:
    type:
      - string
      - 'null'
  fetchUrl:
    type:
      - string
      - 'null'
