type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  description: 
    type: string
    nullable: true
  code: 
    type: string
  type: 
    type: string
  active: 
    type: boolean
  deleted: 
    type: boolean
  autoSyncOnLogin: 
    type: boolean
  externalLogin: 
    type: boolean
  allowCustomMappings: 
    type: boolean
  account: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
  defaultAccountRole: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
      authority: 
        type: string
  config: 
    type: object
    properties: 
      url: 
        type: string
      domain: 
        type: string
      useSSL: 
        type: string
      bindingUsername: 
        type: string
      bindingPassword: 
        type: string
      requiredGroup: 
        type: string
      requiredGroupDN: 
        type: string
      searchMemberGroups: 
        type: boolean
      bindingPasswordHash: 
        type: string
  roleMappings: 
    type: array
    items: 
      type: object
      properties: 
        sourceRoleName: 
          type: string
        sourceRoleFqn: 
          type: string
        mappedRole: 
          type: object
          properties: 
            id: 
              type: integer
              format: int64
            name: 
              type: string
            authority: 
              type: string
  subdomain: 
    type: string
  loginURL: 
    type: string
  providerSettings: 
    type: object
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time