type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  description: 
    type: string
  code: 
    type: string
  type: 
    type: string
  active: 
    type: boolean
  deleted: 
    type: boolean
  autoSyncOnLogin: 
    type: boolean
  externalLogin: 
    type: boolean
  allowCustomMappings: 
    type: boolean
  manualRoleAssignment:
    type: boolean
  account: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
  defaultAccountRole: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
      authority: 
        type: string
  config: 
    type: object
    properties: 
      noninteractive: 
        type: boolean
      loginUrl: 
        type: string
      logoutUrl: 
        type: string
      encryptionAlgo: 
        type: string
      encryptionKey: 
        type: string
      requiredAttributeValue: 
        type: string
  roleMappings: 
    type: array
    items:
      type: object
  subdomain: 
    type: string
  loginURL: 
    type: string
  providerSettings: 
    type: object
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
