type: object
properties:
  noAgent:
    type: boolean
    nullable: true
    description: Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.
    default: false
  isEC2:
    type: string
    description: Amazon Cloud Type
    default: "false"
  availabilityId:
    type: string
    description: Amazon Zone
  securityId:
    type: string
    description: Security Group
  publicIpType:
    type: string
    description: Public IP
    example: "elasticIp"
  instanceProfile:
    type: string
    description: IAM Profile
  kmsKeyId:
    type: string
    description: KMS Key ID
