type: object
properties:
  noAgent:
    type: [ boolean, 'null' ]
    description: Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.
    default: false
  resourcePoolId:
    type: string
    description: id of the resource group to be used, can be prefixed with `pool-`. A resource pool group can be specified instead by prefixing its ID with `poolGroup-`.
  hostId:
    type: string
    description: Specific host to deploy to if so desired.
  smbiosAssetTag:
    type: string
    description: Sets the asset tag on the SMBIOS for use by the guest operating system. If left blank, the virtual machine name will be used.
  nestedVirtualization:
    type: string
    description: Enable Nested Virtualization
    default: "off"
    enum:
      - "on"
      - "off"
  vmwareFolderId:
    type: string
    description: VMWare Folder External ID (as a String) or ID (as an Integer or String)
