type: object
required:
  - integration
properties:
  integration:
    type: object
    required:
      - name
      - type
      - serviceUrl
      - serviceUsername
    properties:
      name: 
        type: string
        description: Name, a unique identifier for the integration
        example: Sample Integration
      type:
        type: string
        description: Integration Type Code
        enum:
        - git
      serviceUrl:
        type: string
        description: Git URL
      serviceUsername:
        type: string
        description: Username
      servicePassword:
        type: string
        description: Password
      serviceToken:
        type: string
        description: Access Token
      serviceKey:
        type: integer
        format: int64
        description: Key Pair ID
      config:
        type: object
        properties:
          defaultBranch:
            type: string
            description: Default Branch
            enum:
              - main
              - master
          cacheEnabled:
            type: boolean
            description: Enable Git Repository Caching