type: object
required:
  - integration
properties:
  integration:
    type: object
    required:
      - name
      - type
    properties:
      name: 
        type: string
        description: Name, a unique identifier for the integration
        example: Sample Integration
      type:
        type: string
        description: Integration Type Code
        enum:
        - ansible
        - ansibleTower
        - bindDns
        - chef
        - cherwell
        - cypher
        - docker.registry
        - git
        - github
        - microsoft.dns
        - powerDns
        - puppet
        - remedy
        - amazonDns
        - saltMaster
        - serviceNow
        - vro
      enabled:
        type: boolean
        description: Set `true` to enable integration
      refresh:
        type: boolean
        description: |
          Pass `false` to skip refresh. 
          By default, refresh is done on update, when it is supported by the integration type.
        default: true
      credential:
        description: |
          Map containing Credential ID or the default {"type": "local"} 
          which means use the values set in the local task options username and password instead of associating a credential.
        oneOf: 
          - type: object
            properties: 
              type:
                type: string
                enum:
                  - local                              
          - type: object
            properties:
              id:
                type: integer
                format: int64