type: object
properties: 
  enabled: 
    type: boolean
  retentionDays: 
    type: string
  syslogRules: 
    type: array
    nullable: true
    example: '{"name": "foo","rule":"*.* @@localhost:4567"}'
  integrations: 
    type: array
    nullable: true