type: object
properties:
  autoManageChecks:
    type: boolean
    description: Auto Create Checks
  availabilityTimeFrame:
    type:
      - integer
      - 'null'
    format: int32
    description: Availability Time Frame. The number of days availability should be calculated for. Changes will not take effect until your checks have passed their check interval.
    example: 30
  availabilityPrecision:
    type:
      - integer
      - 'null'
    format: int32
    description: Availability Precision. The number of decimal places availability should be displayed in. Can be anywhere between 0 and 5.
    example: 3
  defaultCheckInterval:
    type:
      - integer
      - 'null'
    format: int32
    description: Default Check Interval. The number of minutes to use as the default interval to use when creating new checks.
    example: 5
  serviceNow:
    type: object
    description: Service Now Settings
    properties:
      enabled:
        type: boolean
        description: Enabled
      integration:
        type: object
        description: Service Now Integration Object
        properties:
          id:
            type: integer
            format: int64
            description: Service Now Integration ID
          name:
            type: string
            description: Service Now Integration Name
      newIncidentAction:
        description: New Incident Action
        oneOf:
          - type: string
            example: create
            enum:
              - create
              - none
          - type: 'null'
      closeIncidentAction:
        description: Close Incident Action
        oneOf:
          - type: string
            example: close
            enum:
              - close
              - activity
              - none
          - type: 'null'
      infoMapping:
        description: Info Mapping
        oneOf:
          - type: string
            example: low
            enum:
              - low
              - medium
              - high
          - type: 'null'
      warningMapping:
        description: Warning Mapping
        oneOf:
          - type: string
            example: medium
            enum:
              - low
              - medium
              - high
          - type: 'null'
      criticalMapping:
        description: Critical Mapping
        oneOf:
          - type: string
            example: high
            enum:
              - low
              - medium
              - high
          - type: 'null'
