type: object
required:
  - mtu
  - autoCreate
properties: 
  mtu:
    type: string
    description: GCP MTU
    default: "1460"
    enum:
      - "1460"
      - "1500"
  autoCreate:
    type: boolean
    description: Auto create subnets
    default: true
