type: object
properties:
  allowZoneSelection: 
    type: boolean
  allowServerSelection: 
    type: boolean
  requireEnvironments: 
    type: boolean
  showPricing: 
    type: boolean
  hideDatastoreStats: 
    type: boolean
  crossTenantNamingPolicies: 
    type: boolean
  reuseSequence: 
    type: boolean
  cloudInitUsername: 
    type: string
  cloudInitPassword: 
    type: string
  cloudInitKeyPair: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
  windowsPassword: 
    type: [ string, 'null' ]
  pxeRootPassword: 
    type: [ string, 'null' ]
  defaultTemplateType: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
      code: 
        type: string
  deployStorageProvider: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
