type: object
additionalProperties: false
properties:
  username:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  jsScript:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
title: Java Task Config
