type: object
additionalProperties: false
properties:
  sshKey:
    type:
      - string
      - 'null'
    format: password
  localScriptGitRef:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  vroBody:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
    format: password
  passwordHash:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
title: vRealize Orchestrator Task Config
