type: object
additionalProperties: false
properties:
  host:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  containerScriptId:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  containerScript:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
title: Library Script Task Config
