type: object
additionalProperties: false
properties:
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  ansibleTowerGitRef:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  ansibleGroup:
    type:
      - string
      - 'null'
  ansibleTowerExecuteMode:
    type: string
  localScriptGitRef:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
title: Ansible Tower Task Config
