type: object
additionalProperties: false
properties:
  username:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  containerTemplateId:
    type:
      - string
      - 'null'
  containerTemplate:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
title: Library Template Task Config
