type: object
properties: 
  id: 
    type: integer
    format: int64
  accountId: 
    type: integer
    format: int64
  name: 
    type: string
  code: 
    type: string
    nullable: true
  taskType: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      code: 
        type: string
        enum: 
          - conditionalWorkflow
      name: 
        type: string
  labels:
    type: array
    items: 
      type: string
  visibility:
    type: string
  taskOptions: 
    type: object
    additionalProperties: false
    required: 
      - conditionalScript
      - ifOperationalWorkflowId
      - elseOperationalWorkflowId
    properties: 
      conditionalScript:
        type: string
        description: Conditional Script (JS)
      ifOperationalWorkflowId: 
        type: string
        nullable: true
        description: If Operational Workflow ID
      ifOperationalWorkflowName: 
        type: string
        nullable: true
        description: If Operational Workflow Name
      elseOperationalWorkflowId: 
        type: string
        nullable: true
        description: Else Operational Workflow ID
      elseOperationalWorkflowName: 
        type: string
        nullable: true
        description: Else Operational Workflow Name
  resultType: 
    type: string
    nullable: true
  executeTarget: 
    type: string
  retryable: 
    type: boolean
  retryCount: 
    type: integer
    format: int64
  retryDelaySeconds: 
    type: integer
    format: int64
  allowCustomConfig: 
    type: boolean
  credential: 
    type: object
    properties: 
      type: 
        type: string
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
