type: object
additionalProperties: false
properties:
  localScriptGitId:
    type:
      - string
      - 'null'
  emailSkipTemplate:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  emailSubject:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
    format: password
  passwordHash:
    type:
      - string
      - 'null'
  emailAddress:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
title: Email Task Config
