type: object
additionalProperties: false
properties:
  pythonArgs:
    type:
      - string
      - 'null'
  pythonBinary:
    type:
      - string
      - 'null'
  pythonAdditionalPackages:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
    format: password
  password:
    type:
      - string
      - 'null'
    format: password
  passwordHash:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
title: Python Task Config
