type: object
additionalProperties: false
properties:
  port:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  puppetEnvironment:
    type:
      - string
      - 'null'
  puppetNodeName:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
title: Puppet Task Config
