type: object
additionalProperties: false
properties:
  password:
    type:
      - string
      - 'null'
    format: password
  passwordHash:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
    format: password
  port:
    type:
      - string
      - 'null'
title: Restart Task Config
