type: object
additionalProperties: false
required:
  - operationalWorkflowId
properties:
  operationalWorkflowId:
    type:
      - string
      - 'null'
    description: Operational Workflow ID
  operationalWorkflowName:
    type:
      - string
      - 'null'
    description: Operational Workflow Name
title: Nested Workflow Task Config
