type: object
additionalProperties: false
properties:
  localScriptGitRef:
    type:
      - string
      - 'null'
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
title: Groovy Task Config
