type: object
additionalProperties: false
properties:
  webPassword:
    type:
      - string
      - 'null'
    format: password
  webPasswordHash:
    type:
      - string
      - 'null'
  localScriptGitId:
    type:
      - string
      - 'null'
  localScriptGitRef:
    type:
      - string
      - 'null'
  webUser:
    type:
      - string
      - 'null'
  webBody:
    type:
      - string
      - 'null'
  webHeaders:
    type: string
  password:
    type:
      - string
      - 'null'
  passwordHash:
    type:
      - string
      - 'null'
  username:
    type:
      - string
      - 'null'
  ignoreSSL:
    type:
      - string
      - 'null'
  webMethod:
    type:
      - string
      - 'null'
  webUrl:
    type:
      - string
      - 'null'
  host:
    type:
      - string
      - 'null'
  port:
    type:
      - string
      - 'null'
  sshKey:
    type:
      - string
      - 'null'
    format: password
title: HTTP Task Config
