type: object
properties: 
  username: 
    type: string
    description: Username
  email: 
    type: string
    description: Email
  firstName: 
    type: string
    description: First Name
  lastName: 
    type: string
    description: Last Name
  password:
    type: string
    description: Change your password
  linuxUsername: 
    type: string
    description: Linux Username
  linuxPassword: 
    type: string
    description: Linux Password
  linuxKeyPairId: 
    type: integer
    format: int64
    description: Linux Key Pair ID
  windowsUsername: 
    type: string
    description: Windows Username
  windowsPassword: 
    type: string
    description: Windows Password
  receiveNotifications: 
    type: boolean
    description: Receive Notifications (true or false)
  defaultGroup: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
        description: Default Group ID
  defaultCloud: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
        description: Default Cloud ID
  defaultPersona: 
    type: object
    properties: 
      code: 
        type: string
        description: Default Persona code
        enum: 
          - standard
          - serviceCatalog
          - vdi
