type: object
properties:
  user: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      username: 
        type: string
      firstName: 
        type: string
      lastName: 
        type: string
      email: 
        type: string
      linuxUsername: 
        type: string
      linuxPassword: 
        type: string
      linuxKeyPairId: 
        type: integer
        format: int64
        nullable: true
      windowsUsername: 
        type: string
      windowsPassword: 
        type: string
      avatar: 
        type: string
      desktopBackground: 
        type: string
      receiveNotifications: 
        type: boolean
      defaultGroup: 
        type: object
        properties: 
          id: 
            type: integer
            format: int64
          name: 
            type: string
      defaultCloud: 
        type: object
        properties: 
          id: 
            type: integer
            format: int64
          name: 
            type: string
      defaultPersona: 
        type: object
        properties: 
          id: 
            type: integer
            format: int64
          code: 
            type: string
          name: 
            type: string
      isUsing2FA: 
        type: boolean
      tenant: 
        type: object
        properties: 
          id: 
            type: integer
            format: int64
          name: 
            type: string
  accessTokens: 
    type: array
    items: 
      type: object
      properties: 
        clientId: 
          type: string
        username: 
          type: string
        expiration: 
          type: string
          format: date-time
        tokenType: 
          type: string
        maskedAccessToken: 
          type: string
        maskedRefreshToken: 
          type: string
