type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  type: 
    type: string
  description: 
    type: [ string, 'null' ]
  labels:
    type: [ array, 'null' ]
    items: 
      type: string
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
  accountId: 
    type: integer
    format: int64
  platform: 
    type: [ string, 'null' ]
  visibility: 
    type: string
  allowCustomConfig: 
    type: boolean
  tasks: 
    type: array
    items: 
      type: integer
      format: int64
  optionTypes: 
    type: [ array, 'null' ]
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        name: 
          type: string
        description: 
          type: [ string, 'null' ]
        code: 
          type: string
        fieldName: 
          type: string
        fieldLabel: 
          type: string
        fieldCode: 
          type: [ string, 'null' ]
        fieldContext: 
          type: string
        fieldGroup: 
          type: [ string, 'null' ]
        fieldClass: 
          type: [ string, 'null' ]
        fieldAddOn: 
          type: [ string, 'null' ]
        fieldComponent: 
          type: [ string, 'null' ]
        fieldInput: 
          type: [ string, 'null' ]
        placeHolder: 
          type: [ string, 'null' ]
        verifyPattern: 
          type: [ string, 'null' ]
        helpBlock: 
          type: [ string, 'null' ]
        helpBlockFieldCode: 
          type: [ string, 'null' ]
        defaultValue: 
          type: [ string, 'null' ]
        optionSource: 
          type: [ string, 'null' ]
        optionSourceType: 
          type: [ string, 'null' ]
        optionList: 
          type: [ object, 'null' ]
          properties: 
            id:
              type: integer
              format: int64
            name:
              type: string
        type: 
          type: string
        advanced: 
          type: boolean
        required: 
          type: boolean
        exportMeta: 
          type: boolean
        editable: 
          type: boolean
        creatable: 
          type: boolean
        config: 
          type: object
        displayOrder: 
          type: integer
          format: int64
        wrapperClass: 
          type: [ string, 'null' ]
        enabled: 
          type: boolean
        noBlank: 
          type: boolean
        dependsOnCode: 
          type: [ string, 'null' ]
        visibleOnCode: 
          type: [ string, 'null' ]
        requireOnCode: 
          type: [ string, 'null' ]
        contextualDefault: 
          type: boolean
        displayValueOnDetails: 
          type: [ boolean, 'null' ]
        showOnCreate: 
          type: [ boolean, 'null' ]
        showOnEdit: 
          type: [ boolean, 'null' ]
        localCredential: 
          type: [ string, 'null' ]
  taskSetTasks: 
    type: array
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        taskPhase: 
          type: string
        taskOrder: 
          type: integer
          format: int64
        task: 
          type: object
          properties: 
            id: 
              type: integer
              format: int64
            accountId: 
              type: integer
              format: int64
            name: 
              type: string
            code: 
              type: [ string, 'null' ]
            taskType: 
              type: [ object, 'null' ]
              properties: 
                id: 
                  type: integer
                  format: int64
                code: 
                  type: string
                name: 
                  type: string
            labels:
              type: [ array, 'null' ]
              items: 
                type: string
            taskOptions: 
              type: [ object, 'null' ]
              properties: 
                localScriptGitRef: 
                  type: [ string, 'null' ]
                username: 
                  type: [ string, 'null' ]
                localScriptGitId: 
                  type: [ string, 'null' ]
                host: 
                  type: [ string, 'null' ]
                sshKey: 
                  type: [ string, 'null' ]
                port: 
                  type: [ string, 'null' ]
                password: 
                  type: [ string, 'null' ]
                passwordHash: 
                  type: [ string, 'null' ]
                shell.sudo: 
                  type: [ string, 'null' ]
            file: 
              type: [ object, 'null' ]
              properties: 
                id: 
                  type: integer
                  format: int64
                sourceType: 
                  type: string
                contentRef: 
                  type: [ string, 'null' ]
                contentPath: 
                  type: [ string, 'null' ]
                repository: 
                  type: [ object, 'null' ]
                  properties: 
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                content: 
                  type: [ string, 'null' ]
            resultType: 
              type: [ string, 'null' ]
            executeTarget: 
              type: string
            retryable: 
              type: boolean
            retryCount: 
              type: integer
              format: int64
            retryDelaySeconds: 
              type: integer
              format: int64
            allowCustomConfig: 
              type: boolean
            dateCreated: 
              type: string
              format: date-time
            lastUpdated: 
              type: string
              format: date-time
