type: object
properties: 
  id: 
    type: integer
    format: int64
  name: 
    type: string
  type: 
    type: string
  description: 
    type: string
    nullable: true
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time
  accountId: 
    type: integer
    format: int64
  platform: 
    type: string
    nullable: true
  visibility: 
    type: string
  allowCustomConfig: 
    type: boolean
  tasks: 
    type: array
    items: 
      type: integer
      format: int64
  optionTypes: 
    type: array
    nullable: true
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        name: 
          type: string
        description: 
          type: string
          nullable: true
        code: 
          type: string
        fieldName: 
          type: string
        fieldLabel: 
          type: string
        fieldCode: 
          type: string
          nullable: true
        fieldContext: 
          type: string
        fieldGroup: 
          type: string
          nullable: true
        fieldClass: 
          type: string
          nullable: true
        fieldAddOn: 
          type: string
          nullable: true
        fieldComponent: 
          type: string
          nullable: true
        fieldInput: 
          type: string
          nullable: true
        placeHolder: 
          type: string
          nullable: true
        verifyPattern: 
          type: string
          nullable: true
        helpBlock: 
          type: string
          nullable: true
        helpBlockFieldCode: 
          type: string
          nullable: true
        defaultValue: 
          type: string
          nullable: true
        optionSource: 
          type: string
          nullable: true
        optionSourceType: 
          type: string
          nullable: true
        optionList: 
          type: object
          nullable: true
          properties: 
            id:
              type: integer
              format: int64
            name:
              type: string
        type: 
          type: string
        advanced: 
          type: boolean
        required: 
          type: boolean
        exportMeta: 
          type: boolean
        editable: 
          type: boolean
        creatable: 
          type: boolean
        config: 
          type: object
        displayOrder: 
          type: integer
          format: int64
        wrapperClass: 
          type: string
          nullable: true
        enabled: 
          type: boolean
        noBlank: 
          type: boolean
        dependsOnCode: 
          type: string
          nullable: true
        visibleOnCode: 
          type: string
          nullable: true
        requireOnCode: 
          type: string
          nullable: true
        contextualDefault: 
          type: boolean
        displayValueOnDetails: 
          type: boolean
          nullable: true
        showOnCreate: 
          type: boolean
          nullable: true
        showOnEdit: 
          type: boolean
          nullable: true
        localCredential: 
          type: string
          nullable: true
  taskSetTasks: 
    type: array
    items: 
      type: object
      properties: 
        id: 
          type: integer
          format: int64
        taskPhase: 
          type: string
        taskOrder: 
          type: integer
          format: int64
        task: 
          type: object
          properties: 
            id: 
              type: integer
              format: int64
            accountId: 
              type: integer
              format: int64
            name: 
              type: string
            code: 
              type: string
              nullable: true
            taskType: 
              type: object
              nullable: true
              properties: 
                id: 
                  type: integer
                  format: int64
                code: 
                  type: string
                name: 
                  type: string
            taskOptions: 
              type: object
              nullable: true
              properties: 
                localScriptGitRef: 
                  type: string
                  nullable: true
                username: 
                  type: string
                  nullable: true
                localScriptGitId: 
                  type: string
                  nullable: true
                host: 
                  type: string
                  nullable: true
                sshKey: 
                  type: string
                  nullable: true
                port: 
                  type: string
                  nullable: true
                password: 
                  type: string
                  nullable: true
                passwordHash: 
                  type: string
                  nullable: true
                shell.sudo: 
                  type: string
                  nullable: true
            file: 
              type: object
              nullable: true
              properties: 
                id: 
                  type: integer
                  format: int64
                sourceType: 
                  type: string
                contentRef: 
                  type: string
                  nullable: true
                contentPath: 
                  type: string
                  nullable: true
                repository: 
                  type: object
                  nullable: true
                  properties: 
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                content: 
                  type: string
                  nullable: true
            resultType: 
              type: string
              nullable: true
            executeTarget: 
              type: string
            retryable: 
              type: boolean
            retryCount: 
              type: integer
              format: int64
            retryDelaySeconds: 
              type: integer
              format: int64
            allowCustomConfig: 
              type: boolean
            dateCreated: 
              type: string
              format: date-time
            lastUpdated: 
              type: string
              format: date-time