type: object
properties: 
  apiUrl: 
    type: string
  username: 
    type: string
  password: 
    type: [ string, 'null' ]
  datacenter: 
    type: string
  cluster: 
    type: string
  resourcePoolId: 
    type: string
  resourcePool: 
    type: string
  rpcMode: 
    type: string
  hideHostSelection: 
    type: string
  importExisting: 
    type: string
  enableVnc: 
    type: string
  enableDiskTypeSelection: 
    type: [ string, 'null' ]
  enableNetworkTypeSelection: 
    type: string
  diskStorageType: 
    type: [ string, 'null' ]
  applianceUrl: 
    type: [ string, 'null' ]
  datacenterName: 
    type: [ string, 'null' ]
  networkServer.id: 
    type: string
      # oneOf:
      # - type: string
      # - type: integer
      #   format: int64
  networkServer: 
    type: object
    properties: 
      id:
        type: string
        # oneOf:
        # - type: string
        # - type: integer
        #   format: int64
  securityMode: 
    type: string
  certificateProvider: 
    type: [ string, 'null' ]
  backupMode: 
    type: [ string, 'null' ]
  replicationMode: 
    type: [ string, 'null' ]
  dnsIntegrationId: 
    type: [ string, 'null' ]
  configCmdbId: 
    type: [ string, 'null' ]
  configManagementId: 
    type: [ string, 'null' ]
  configCmId: 
    type: [ string, 'null' ]
  securityServer: 
    type: [ string, 'null' ]
  serviceRegistryId: 
    type: [ string, 'null' ]
  kubeUrl: 
    type: [ string, 'null' ]
  apiVersion: 
    type: [ string, 'null' ]
  datacenterId: 
    type: [ string, 'null' ]
  configCmdbDiscovery: 
    type: boolean
  distributedWorkerId: 
    type: [ string, 'null' ]
  passwordHash: 
    type: [ string, 'null' ]
