type: object
properties:
  endpoint:
    type: string
  accessKey:
    type: string
  secretKey:
    type: string
  useHostCredentials:
    type: string
  stsAssumeRole:
    type: string
  isVpc:
    type: string
  vpc:
    type: string
  imageStoreId:
    type: string
  ebsEncryption:
    type: string
  costingReport:
    type: string
  costingFolder:
    type: string
  costingBucket:
    type: string
  costingBucketName:
    type: string
  costingRegion:
    type: string
  costingAccessKey:
    type: string
  costingSecretKey:
    type:
      - string
      - 'null'
  costingReportName:
    type: string
  applianceUrl:
    type: string
  datacenterName:
    type: string
  networkServer.id:
    type: string
  networkServer:
    type: object
    properties:
      id:
        type: string
  securityServer:
    type:
      - string
      - 'null'
  certificateProvider:
    type: string
  backupMode:
    type: string
  replicationMode:
    type: string
  dnsIntegrationId:
    type: string
  serviceRegistryId:
    type: string
  configManagementId:
    type: string
  configCmdbDiscovery:
    type: boolean
  secretKeyHash:
    type: string
  costingSecretKeyHash:
    type:
      - string
      - 'null'
