type: object
properties:
  apiUrl:
    type: string
  username:
    type: string
  password:
    type: string
    nullable: true
  apiVersion:
    type: string
    nullable: true
  datacenter:
    type: string
  cluster:
    type: string
  resourcePoolId:
    type: string
  resourcePool:
    type: string
  rpcMode:
    type: string
  importExisting:
    type: string
  enableVnc:
    type: string
  enableDiskTypeSelection:
    type: string
    nullable: true
  enableStorageTypeSelection:
    type: string
  enableNetworkTypeSelection:
    type: string
  diskStorageType:
    type: string
    nullable: true
  applianceUrl:
    type: string
    nullable: true
  datacenterName:
    type: string
    nullable: true
  networkServer.id:
    type: string
      # oneOf:
      # - type: string
      # - type: integer
      #   format: int64
  networkServer:
    type: object
    properties:
      id:
        type: string
        # oneOf:
        # - type: string
        # - type: integer
        #   format: int64
  securityServer:
    type: string
    nullable: true
  securityMode:
    type: string
  certificateProvider:
    type: string
    nullable: true
  backupMode:
    type: string
    nullable: true
  replicationMode:
    type: string
    nullable: true
  serviceRegistryId:
    type: string
    nullable: true
  configCmdbDiscovery:
    type: boolean
  datacenterId:
    type: string
    nullable: true
  clusterRef:
    type: string
  kubeUrl:
    type: string
    nullable: true
  distributedWorkerId:
    type: string
    nullable: true
  configManagementId:
    type: string
    nullable: true
  configCmdbId:
    type: string
    nullable: true
  configCmId:
    type: string
    nullable: true
  passwordHash:
    type: string
    nullable: true
  hideHostSelection:
    type: string
  dnsIntegrationId:
    type: string
    nullable: true
