type: object
properties:
  privateKey:
    type: string
  clientEmail:
    type: string
  projectId:
    type: string
  googleRegionId:
    type: string
  importExisting:
    type: string
  applianceUrl:
    type: string
  datacenterName:
    type: string
  networkServer.id:
    type: string
  networkServer:
    type: object
    properties:
      id:
        type: string
  securityServer:
    type:
      - string
      - 'null'
  certificateProvider:
    type:
      - string
      - 'null'
  backupMode:
    type:
      - string
      - 'null'
  replicationMode:
    type:
      - string
      - 'null'
  dnsIntegrationId:
    type:
      - string
      - 'null'
  serviceRegistryId:
    type:
      - string
      - 'null'
  configManagementId:
    type:
      - string
      - 'null'
  privateKeyHash:
    type:
      - string
      - 'null'
