# .github/workflows/readme-io.yml

name: Sync OpenAPI to ReadMe
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get README_VERSION_ID
        env:
          IDJSON: ${{ secrets.README_ID_JSON }}
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          README_VERSION_ID=$(python3 -c 'import json,os;print(json.loads(os.environ.get("IDJSON"))[os.environ.get("GITHUB_REF_NAME")])')
          idsize=${#README_VERSION_ID}
          if [ $idsize -lt 6 ]; then
            echo "No ID found"
            exit 1
          fi
          echo "::add-mask::$README_VERSION_ID"
          echo "README_VERSION_ID=${README_VERSION_ID}" >> $GITHUB_ENV
      - name: node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: lint with redocly
        run: npx @redocly/cli lint openapi.yaml
      - name: bundle with redocly
        run: npx @redocly/cli bundle openapi.yaml > bundled.yaml
      - uses: readmeio/rdme@7.3.0
        with:
          rdme: openapi bundled.yaml --key=${{ secrets.README_TOKEN }} --id=$README_VERSION_ID
