# .github/workflows/readme-io.yml

name: Sync OpenAPI to ReadMe
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/rdme@7.3.0
        with:
          rdme: openapi openapi.yaml --key=${{ secrets.README_TOKEN }} --id=${{ secrets.README_ID }}
